export const addActions = {
    ADD_NAME: "ADD_NAME",
    ADD_LAST_NAME: "ADD_LAST_NAME",
    ADD_PASSWORD: "ADD_PASSWORD",
    ADD_EMAIL: "ADD_EMAIL",
    EMAIL_PARSER: "EMAIL_PARSER",
    PASSWORD_PARSER: "PASSWORD_PARSER"
}